language: node_js
sudo: true
node_js: 8
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm test
deploy:
- provider: script
  skip_cleanup: true
  script:
  - bx-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/botkit-middleware
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 8